development: &development
  :elasticsearch_endpoint: <%= ENV['METASLURP_DEV_ELASTICSEARCH_ENDPOINT'] %>
  :time_zone: <%= ENV['METASLURP_TIME_ZONE'] %>

test:
  :elasticsearch_endpoint: <%= ENV['METASLURP_TEST_ELASTICSEARCH_ENDPOINT'] %>
  :time_zone: <%= ENV['METASLURP_TIME_ZONE'] %>

production:
  :elasticsearch_endpoint: <%= ENV['METASLURP_PROD_ELASTICSEARCH_ENDPOINT'] %>
  :time_zone: <%= ENV['METASLURP_TIME_ZONE'] %>
