default: &default
  :dls_url: <%= ENV['DLS_URL'] %>
  :elasticsearch_endpoint: <%= ENV['ELASTICSEARCH_ENDPOINT'] %>
  :time_zone: <%= ENV['TIME_ZONE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
